services:
  postgres:
    image: postgres:14
    container_name: irglobal_postgres
    restart: always
    environment:
      POSTGRES_USER: irglobal
      POSTGRES_PASSWORD: irglobal123
      POSTGRES_DB: irglobal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - irglobal_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: irglobal_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@irglobal.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - irglobal_network

volumes:
  postgres_data:
    name: irglobal_postgres_data

networks:
  irglobal_network:
    name: irglobal_network 