// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Autentica o usuário no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Autentica o usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Registra um novo usuário no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registrar um novo usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/transaction/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Adiciona uma nova Transação ao sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Adiciona uma nova Transação",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token de autenticação",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da transação",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transaction.AddTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transação criada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/domain.Transaction"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/transaction/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes a Transaction from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Deletes a Transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Transaction details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transaction.DeleteTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction successfully deleted",
                        "schema": {
                            "$ref": "#/definitions/domain.Transaction"
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "senha123"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "João Silva"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "senha123"
                }
            }
        },
        "domain.AssetType": {
            "type": "string",
            "enum": [
                "CRYPTO",
                "STOCK",
                "ETF"
            ],
            "x-enum-varnames": [
                "Crypto",
                "Stock",
                "ETF"
            ]
        },
        "domain.OperationType": {
            "type": "string",
            "enum": [
                "BUY",
                "SELL"
            ],
            "x-enum-varnames": [
                "Buy",
                "Sell"
            ]
        },
        "domain.Transaction": {
            "type": "object",
            "properties": {
                "asset_symbol": {
                    "description": "Símbolo do ativo",
                    "type": "string"
                },
                "asset_type": {
                    "description": "Tipo de ativo",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.AssetType"
                        }
                    ]
                },
                "created_at": {
                    "description": "Data de criação",
                    "type": "string"
                },
                "id": {
                    "description": "UUID",
                    "type": "string"
                },
                "operation_date": {
                    "description": "Data da operação",
                    "type": "string"
                },
                "price_in_brl": {
                    "description": "Preço em BRL",
                    "type": "number"
                },
                "price_in_usd": {
                    "description": "Preço em USD",
                    "type": "number"
                },
                "quantity": {
                    "description": "Quantidade",
                    "type": "number"
                },
                "total_cost_brl": {
                    "description": "Custo total em USD",
                    "type": "number"
                },
                "total_cost_usd": {
                    "description": "Custo total em USD",
                    "type": "number"
                },
                "type": {
                    "description": "Tipo de operação",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.OperationType"
                        }
                    ]
                },
                "usd_brl_rate": {
                    "description": "Taxa de câmbio USD/BRL",
                    "type": "number"
                },
                "user_id": {
                    "description": "UUID do usuário",
                    "type": "string"
                }
            }
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "transaction.AddTransactionRequest": {
            "type": "object",
            "required": [
                "asset_symbol",
                "asset_type",
                "operation_date",
                "price_in_usd",
                "quantity",
                "type"
            ],
            "properties": {
                "asset_symbol": {
                    "description": "Símbolo do ativo",
                    "type": "string",
                    "example": "AAPL"
                },
                "asset_type": {
                    "description": "Tipo de ativo",
                    "enum": [
                        "CRYPTO",
                        "STOCK",
                        "ETF"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.AssetType"
                        }
                    ]
                },
                "operation_date": {
                    "description": "Data da operação",
                    "type": "string"
                },
                "price_in_usd": {
                    "description": "Preço em USD",
                    "type": "number",
                    "minimum": 0
                },
                "quantity": {
                    "description": "Quantidade",
                    "type": "number",
                    "minimum": 0
                },
                "type": {
                    "description": "Tipo de operação",
                    "enum": [
                        "BUY",
                        "SELL"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.OperationType"
                        }
                    ]
                }
            }
        },
        "transaction.DeleteTransactionRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ss1dofn-oqin3vdkf-alds8foi"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "IRGlobal API",
	Description:      "API para o sistema IRGlobal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
