basePath: /
definitions:
  auth.LoginRequest:
    properties:
      email:
        example: joao@example.com
        type: string
      password:
        example: senha123
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  auth.RegisterRequest:
    properties:
      email:
        example: joao@example.com
        type: string
      name:
        example: João Silva
        type: string
      password:
        example: senha123
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  domain.AssetType:
    enum:
    - CRYPTO
    - STOCK
    - ETF
    type: string
    x-enum-varnames:
    - Crypto
    - Stock
    - ETF
  domain.OperationType:
    enum:
    - BUY
    - SELL
    type: string
    x-enum-varnames:
    - Buy
    - Sell
  domain.Position:
    properties:
      asset_symbol:
        description: Símbolo do ativo
        type: string
      asset_type:
        allOf:
        - $ref: '#/definitions/domain.AssetType'
        description: Tipo de ativo
      average_cost_brl:
        description: Preço em BRL
        type: number
      average_cost_usd:
        description: Preço em BRL
        type: number
      created_at:
        description: Data de criação
        type: string
      id:
        description: UUID
        type: string
      quantity:
        description: Quantidade
        type: number
      total_cost_brl:
        description: Custo total em USD
        type: number
      total_cost_usd:
        description: Custo total em USD
        type: number
      user_id:
        description: UUID do usuário
        type: string
    type: object
  domain.RealizedPNL:
    properties:
      asset_symbol:
        description: Símbolo do ativo
        type: string
      asset_type:
        allOf:
        - $ref: '#/definitions/domain.AssetType'
        description: Tipo de ativo
      average_cost_brl:
        description: Custo médio em BRL
        type: number
      average_cost_usd:
        description: Custo médio em USD
        type: number
      created_at:
        description: Data de criação
        type: string
      id:
        description: UUID
        type: string
      quantity:
        description: Quantidade
        type: number
      realized_profit_brl:
        description: Lucro realizado em BRL
        type: number
      realized_profit_usd:
        description: Lucro realizado em USD
        type: number
      selling_price_brl:
        description: Preço de venda em BRL
        type: number
      selling_price_usd:
        description: Preço de venda em USD
        type: number
      total_cost_brl:
        description: Custo total em BRL
        type: number
      total_cost_usd:
        description: Custo total em USD
        type: number
      total_value_sold_brl:
        description: Valor total da venda em BRL
        type: number
      total_value_sold_usd:
        description: Valor total da venda em USD
        type: number
      user_id:
        description: UUID do usuário
        type: string
    type: object
  domain.Transaction:
    properties:
      asset_symbol:
        description: Símbolo do ativo
        type: string
      asset_type:
        allOf:
        - $ref: '#/definitions/domain.AssetType'
        description: Tipo de ativo
      created_at:
        description: Data de criação
        type: string
      id:
        description: UUID
        type: string
      operation_date:
        description: Data da operação
        type: string
      price_in_brl:
        description: Preço em BRL
        type: number
      price_in_usd:
        description: Preço em USD
        type: number
      quantity:
        description: Quantidade
        type: number
      total_cost_brl:
        description: Custo total em USD
        type: number
      total_cost_usd:
        description: Custo total em USD
        type: number
      type:
        allOf:
        - $ref: '#/definitions/domain.OperationType'
        description: Tipo de operação
      usd_brl_rate:
        description: Taxa de câmbio USD/BRL
        type: number
      user_id:
        description: UUID do usuário
        type: string
    type: object
  domain.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  transaction.AddTransactionRequest:
    properties:
      asset_symbol:
        description: Símbolo do ativo
        example: AAPL
        type: string
      asset_type:
        allOf:
        - $ref: '#/definitions/domain.AssetType'
        description: Tipo de ativo
        enum:
        - CRYPTO
        - STOCK
        - ETF
        example: STOCK
      operation_date:
        description: Data da operação
        example: "2025-02-11"
        type: string
      price_in_usd:
        description: Preço em USD
        example: 50
        minimum: 0
        type: number
      quantity:
        description: Quantidade
        example: 20
        minimum: 0
        type: number
      type:
        allOf:
        - $ref: '#/definitions/domain.OperationType'
        description: Tipo de operação
        enum:
        - BUY
        - SELL
    required:
    - asset_symbol
    - asset_type
    - operation_date
    - price_in_usd
    - quantity
    - type
    type: object
  transaction.DeleteTransactionRequest:
    properties:
      id:
        example: d081b7c0-b3b6-49ba-a9b7-86b56a65fb89
        type: string
    required:
    - id
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para o sistema IRGlobal
  title: IRGlobal API
  version: "1.0"
paths:
  /RealizedPNL/get:
    get:
      consumes:
      - application/json
      description: Retorna uma lista do PNL para um usuário específico.
      parameters:
      - description: Token de autenticação
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de pnl do usuário
          schema:
            items:
              $ref: '#/definitions/domain.RealizedPNL'
            type: array
        "400":
          description: Dados inválidos
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Lista os Ganhos e Perdas do usuário
      tags:
      - pnl
  /auth/login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário no sistema
      parameters:
      - description: Dados do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Autentica o usuário
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registra um novo usuário no sistema
      parameters:
      - description: Dados do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Registrar um novo usuário
      tags:
      - auth
  /position/get:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de posições para um usuário específico.
      parameters:
      - description: Token de autenticação
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de posições do usuário
          schema:
            items:
              $ref: '#/definitions/domain.Position'
            type: array
        "400":
          description: Dados inválidos
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Lista as posições do usuário
      tags:
      - position
  /transaction/add:
    post:
      consumes:
      - application/json
      description: Adiciona uma nova Transação ao sistema
      parameters:
      - description: Token de autenticação
        in: header
        name: Authorization
        required: true
        type: string
      - description: Dados da transação
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.AddTransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Transação criada com sucesso
          schema:
            $ref: '#/definitions/domain.Transaction'
        "400":
          description: Dados inválidos
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Adiciona uma nova Transação
      tags:
      - transaction
  /transaction/delete:
    delete:
      consumes:
      - application/json
      description: Deletes a Transaction from the system
      parameters:
      - description: Authentication Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Transaction details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transaction.DeleteTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Transaction successfully deleted
          schema:
            $ref: '#/definitions/domain.Transaction'
        "404":
          description: Transaction not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Deletes a Transaction
      tags:
      - transaction
swagger: "2.0"
